name: Run UI tests + create pull request

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the dev_branch branch
  push:
    branches:
    - '!dev_branch'
    - '!master'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  ui_tests:
    runs-on: macos-latest
    steps:
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: checkout
        uses: actions/checkout@v2
        
      - name: run tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          script: ./gradlew connectedCheck
      
  pull_request:
    needs: ui_tests
    runs-on: ubuntu-latest
    steps:
     - name: checkout
       uses: actions/checkout@v2
       
     - name: GitHub Pull Request Action
       uses: repo-sync/pull-request@v2.6
       with:
        destination_branch: "dev_branch"
        github_token: ${{secrets.BASE_SECRET}}
        pr_assignee: "andrzejbogacz"
