name: Run UI tests api 29

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the dev_branch branch
  push:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  test:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
      - name: Build with Gradle
        run: ./gradlew --version

      - name: checkout
        uses: actions/checkout@v2

      - name: run tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 29
          script: ./gradlew connectedCheck

      - uses: actions/checkout@v2
          # Make changes to pull request here
      - name: GitHub Pull Request Action
        uses: repo-sync/pull-request@v2.6
        with:
         destination_branch: "dev_branch"
         github_token: ${{secrets.BASE_SECRET}}
         pr_assignee: "andrzejbogacz"
